### PR TITLE
Add mock location support

### PR DESCRIPTION
**Pull request by moskvax**
I wasn't sure exactly how to go about doing this, although this solution appears to work OK. Setting mock mode in the location provider API has the side-effect of changing the functioning of all other Observables which are using it (actually it changes the source of location information for all users of the API across the whole device, even in other apps). I went with using Subscription state to turn it on and off, but I'm quite new with RxJava and I'm not sure how to encapsulate this kind of global state mutation in a way that seems idiomatic.

### CODE REVIEW

**Comment by moskvax** [comment]
I took another look at this after looking some more at the how the other observables have been are done and realized that it can be done very similarly. This MockLocationObservable is really just a LocationUpdatesObservable that subscribes to the passed-in observable instead of using LocationRequest/LocationListener. Error handling is done in the same way as the geofence observables.

**Comment by mcharmas** [comment]
Great work. Give me some time to take a deeper look into it.

**Comment by mcharmas** [comment]
@moskvax Thanks again. I've fixed some minor things. New version will be released later today.

**Comment by moskvax** [comment]
@mcharmas Awesome! :+1:

**Pull request merged**
