### PR TITLE
Add fallback reverse geocode lookup in case the main geocoder raises …

### PR DESCRIPTION
**Pull request by zoltanf**
…an IOException with "Service not Available". This fallback is useful for devices where reverse geocoder fails for some reason (usually this happens just after google play services update but before the device is restarted).

Addresses issue #86

### CODE REVIEW

**Comment by zoltanf** [comment]
I found a problem in this implementation, because I have explicitly created a new thread. I'm re-writing this to support also scenario where the observer has explicitly set threading model via rxjava.

**Comment by mcharmas** [comment]
@zoltanf I've just took a look at your implementation and my suggestion was just that. Let RxJava manage threats - it is awesome doing it.

I think you can just simplyfy this and implement id passing result of alternative function to onNext with proper error handling.

**Comment by zoltanf** [comment]
Problem is that I can't just do it that simply. The issue is that if the caller does not specify subscribeOn then this is run on the main thread and it fails, as you know networking is not allowed on Android main thread. So, I made a decision three, detect if the observable is running on the main thread then create a new, otherwise just use the alternative function synchronously. Will submit a new PN soon.

**Comment by zoltanf** [comment]
BTW, the sample app in the library uses this approach (runs reverse geocode on main thread)....
So for backward compatibility for all the people that did the same... we have to do this.

**Comment by mcharmas** [comment]
Hmm, you might be right, it's not cleanest solution though.

Maybe cleaner soultion would be to create observable with alternative implementation and set it up to use Schedulers.io() in case on main thread and and subsribe the passed in subscriber. I would prefer to avoid creating new thread by the library.

**Comment by zoltanf** [comment]
Sorry but that's beyond my knowledge of RxJava. I really need this now on a project I'm working on so I will include this fork aar in the main project, I hope you will find a way to integrate this more properly with a auto-fallback.

**Comment by mcharmas** [comment]
@zoltanf ok, thanks for your contribution. I'll try to release new version with this feature in few days.

**Comment by zoltanf** [comment]
@mcharmas Happy to help. Let me know if I can do anything else regarding this. Best of luck and once again thank you for your hard work on this lib.

**Pull request closed without merging**
