### PR TITLE
Add RxJava 2 support

### PR DESCRIPTION
**Pull request by mcharmas**
This PR contains library migrated to RxJava2. I'll try to test it, and merge it later next week. Please test and leave feedback.

### CODE REVIEW

**Comment by vdubedout** [comment]
Can't is be better to keep a separated branch? I don't like long side branches (it's a pain to maintain) but as RXJava 1 is not deprecated and still a lot of persons are using it, it can be usefull to keep.

**Comment by elirangoshen** [comment]
yes good idea @vdubedout 
is there estimation for merge ?

**Comment by doppie** [comment]
Is there any ambition of releasing this as a stable version?

**Comment by jettimadhu** [comment]
@mcharmas When can we expect stable version to support RxJava2.

**Pull request merged**
