### PR TITLE
migrate to rxjava2

### PR DESCRIPTION
**Pull request by elirangoshen**
I did migration to rxjava2 of the library plus the samples.
I checked the samples and library and it seems fine.

I also updated play services, rxjava (to v2) and build tools in gradle.

### CODE REVIEW

**Comment by mhdtouban** [comment]
when will this be shipped?

**Comment by sytolk** [comment]
I suppose that when @elirangoshen add .idea/ folder in .gitignore ;)

**Comment by elirangoshen** [comment]
@sytolk sorry for that amateur move, i forgot :)
i'll definitely fix it !

**Comment by mcharmas** [comment]
@elirangoshen thanks for your contribution. I needed to do a lot of cleanup an changes to your code and created another Pull Request #145 . I'll try to merge it later next week. Please test if you can.

**Comment by elirangoshen** [comment]
thanks and sorry for the mess :)
hope it still contribute something P:
i'll try to test it next week and update

**Comment by jettimadhu** [comment]
@elirangoshen 
When can we expect stable version to support RxJava2.

**Pull request closed without merging**
