### PR TITLE
Activity Recognition

### PR DESCRIPTION
**Pull request by cyrixmorten**
Added two examples to the sample

### CODE REVIEW

**Comment by tehfonsi** [comment]
Activity recognition would be really awesome!

**Comment by mcharmas** [comment]
@cyrixmorten I've just merge your pullrequest with a big bunch of changes. I fucked up merge and rebased your commits and github didn't notice that - sorry. Anyway, version 0.4 is being propagated to maven central and should be available in few hours. Take a look at changes if you are intrested. I did it using BroadcastReceiver and it works well. Thanks for contribution!

**Comment by cyrixmorten** [comment]
Looks great! :) No problem. Hope it will prove to be a valuable feature.

**Comment by cyrixmorten** [comment]
Just successfully migrated to 0.4 of the library.

Do not know if it is due to conflicts with previous code (simply updated the app, did not uninstall) or if there is problems with the Android Activity Recognition code in some situations. However, I had to restart the phone to make it report other activities than still. 

Cheers

**Comment by mcharmas** [comment]
Hmm, I doubt it's library's fault. I mean, all it does it streaming what GMS is delivering - maybe that was caused by GMS problems?

**Comment by cyrixmorten** [comment]
I think you are right.

Just wanted to let you know in case others experience the same, but come to think of it, I think I had a similar problem when using the official example code for activity recognition.

**Pull request closed without merging**
